In [1]:
import tensorflow as tf
import os
import cv2
from matplotlib import pyplot as plt
%matplotlib inline  

In [2]:
tf.enable_eager_execution()

In [ ]:
def get_category_prototypes_from_embeddings(embeddings, labels, class_num):
	class_ids = list(range(class_num))
	class_ids = tf.reshape(tf.constant(class_ids), shape=(len(class_ids), 1))

	indice = tf.equal(labels, class_ids)

	prototypes = tf.map_fn(lambda x : tf.reduce_mean(tf.squeeze(tf.gather(embeddings, tf.where(x)), axis=1), axis=0), indice, dtype=embeddings.dtype)
	return prototypes

In [ ]:
embeddings = tf.constant([[0.5, 2.0, 3.0], [4, 5, 6], [7, 8, 9], [10, 20, 30]], tf.float32)
labels = tf.constant([0, 0, 0, 1], tf.int32)
class_num = 2

In [ ]:
result = get_category_prototypes_from_embeddings(embeddings, labels, class_num)
print(result)

In [4]:
new_embeddings = tf.constant([[10,10, 10 ], [20, 20, 20 ], [30, 30, 30 ], [40,40, 40 ]], tf.float32)
new_labels = tf.constant([0, 0, 1, 1], tf.int32)
class_num = 2

In [ ]:
def get_loss_from_prototypes(embeddings, labels, prototypes, class_num):
	class_ids = list(range(class_num))
	class_ids = tf.reshape(tf.constant(class_ids), shape=(len(class_ids), 1))

	indice = tf.equal(labels, class_ids)

	loss = tf.map_fn(lambda x : tf.reduce_sum( tf.pow(x[0] 
                                                    - tf.squeeze(tf.gather(embeddings, tf.where(x[1])), axis=1), 2) ), (prototypes, indice), dtype=embeddings.dtype)
	return loss

In [5]:
class_ids = list(range(class_num))
class_ids = tf.reshape(tf.constant(class_ids), shape=(len(class_ids), 1))
indice = tf.equal(new_labels, class_ids)
print(indice)

tf.Tensor(
[[ True  True False False]
 [False False  True  True]], shape=(2, 4), dtype=bool)


In [6]:
prototype = tf.constant([[0, 0 , 0 ], [0,0,0]], tf.float32)

In [7]:
minus = prototype[1] - tf.squeeze( tf.gather(new_embeddings, tf.where(indice[1])), axis=1 )

In [8]:
minus

<tf.Tensor: id=21, shape=(2, 3), dtype=float32, numpy=
array([[-30., -30., -30.],
       [-40., -40., -40.]], dtype=float32)>

In [9]:
squared_l2_distance = tf.pow(minus, 2)

In [10]:
squared_l2_distance

<tf.Tensor: id=24, shape=(2, 3), dtype=float32, numpy=
array([[ 899.99994,  899.99994,  899.99994],
       [1600.     , 1600.     , 1600.     ]], dtype=float32)>

In [11]:
loss = tf.reduce_sum(squared_l2_distance, axis=1)
print(loss)

tf.Tensor([2699.9998 4800.    ], shape=(2,), dtype=float32)


In [ ]:
loss = get_loss_from_prototypes(new_embeddings, new_labels, prototype, class_num)

In [ ]:
sess = tf.Session()

In [ ]:
sess.run(loss)

In [ ]:
grad = tf.gradients([loss], [new_embeddings])

In [ ]:
print(sess.run(grad))

In [ ]:
a = tf.constant( [1, 2], tf.float32 )
b = tf.constant( [7, 5], tf.float32 )

c = a*b

In [ ]:
print(c)

In [ ]:
sess = tf.Session()
grad = tf.gradients([c], [a])

In [ ]:
print(sess.run(grad))